In [1]:
import pandas as pd
import numpy as np 

# What is an Array? 
An array is a collection of items stored at contiguous memory locations. The idea is to store multiple items of the same type together. This makes it easier to calculate the position of each element by simply adding an offset to a base value, i.e., the memory location of the first element of the array (generally denoted by the name of the array).

In [2]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [4]:
a2 = a[np.newaxis, :]
a2
print(a2.shape)

(1, 6)


In [5]:
print(a2)
print(a2.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [6]:
a2 = a[: , np.newaxis]
a2

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [7]:
a3 = a2[np.newaxis, :]
print(a3)
print(a3.shape)

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]
(1, 6, 1)


In [8]:
# Creatng an array with numpy

In [9]:
a = np.array([1, 2, 3, 4, 5, 6 ])
a.shape

(6,)

In [10]:
b = np.array([(1, 2, 3), (4, 5, 6)])
b.shape

(2, 3)

# Initialize analysis

In [11]:
zeros = np.zeros((3, 2))
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
ones = np.ones((2, 5 ))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
full = np.full((2, 5), 8)
full

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

# Matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
a = np.array([[1,2,3], [4,5,6]], dtype=int)
a**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [17]:
a1 = np.arange(6).reshape(2,3)
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
a2 = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [19]:
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [20]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [21]:
a1.dtype

dtype('int32')

In [22]:
a2.astype(np.int32)

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a3.dtype

dtype('int32')

In [24]:
#array operations
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [25]:
# scaler operations
#artimetic operations
a2 * 2

array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [26]:
# relational operations
a2 < 5

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [27]:
# vector operations
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [28]:
# min, max, sum, mean, std
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[19., 75.,  2.],
       [ 4., 52., 62.],
       [45., 21., 35.]])

In [29]:
np.max(a1)

75.0

In [30]:
np.min(a1)

2.0

In [31]:
np.sum(a1)

315.0

In [32]:
np.prod(a1)

1215625320000.0

In [33]:
# 0 -> column, 1 -> row
np.max(a1, axis=0)

array([45., 75., 62.])

In [34]:
# 0 -> column, 1 -> row
np.max(a1, axis=1)

array([75., 62., 45.])

In [35]:
# mean, meadian, std, var
np.mean(a1)

35.0

In [36]:
np.median(a1)

35.0

In [37]:
np.std(a1)

24.08318915758459

In [38]:
np.var(a1)

580.0

In [39]:
# trigonometric functions
np.sin(a1), np.cos(a1), np.tan(a1)

(array([[ 0.14987721, -0.38778164,  0.90929743],
        [-0.7568025 ,  0.98662759, -0.7391807 ],
        [ 0.85090352,  0.83665564, -0.42818267]]),
 array([[ 0.98870462,  0.92175127, -0.41614684],
        [-0.65364362, -0.16299078,  0.67350716],
        [ 0.52532199, -0.54772926, -0.90369221]]),
 array([[ 0.15158947, -0.42070095, -2.18503986],
        [ 1.15782128, -6.05327238, -1.09750978],
        [ 1.61977519, -1.52749853,  0.47381472]]))

In [40]:
# dot product
a1 = np.arange(6).reshape(2,3)
a2 = np.arange(6).reshape(3,2)
print(a1)
print(a2)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [41]:
np.dot(a1, a2)

array([[10, 13],
       [28, 40]])

In [42]:
# log nf exponential
np.log(a1)

C:\Users\Muhammad Haroon\AppData\Local\Temp\ipykernel_16160\2963159538.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791]])

In [43]:
np.exp(a1)

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [44]:
# round/ceil/floor
np.round(np.random.random((2, 3))*100)

array([[29., 16., 38.],
       [61., 84.,  4.]])

In [45]:
np.floor(np.random.random((2, 3))*100)

array([[43., 64., 85.],
       [63., 81., 68.]])

In [46]:
np.ceil(np.random.random((2, 3))*100)

array([[61., 15., 69.],
       [81., 13., 18.]])

In [47]:
# indexing and slicing
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [48]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a1[-1], a1[0]

(9, 0)

In [50]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a2[1,2]

6

In [52]:
a2[2,3]

11

In [53]:
a2[1,0]

4

In [54]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [55]:
a3[1,0,1]

5

In [56]:
a3[0,1,0]

2

In [57]:
a3[0,0,0]

0

In [58]:
a3[1,1,0]

6

In [59]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a1[2:5], a1[2:5:2]

(array([2, 3, 4]), array([2, 4]))

In [61]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
a2[0, :]

array([0, 1, 2, 3])

In [63]:
a2[:,2]

array([ 2,  6, 10])

In [64]:
a2[1,:1]

array([4])

In [65]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [66]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [67]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [68]:
a2[1:2, ::3]

array([[4, 7]])

In [69]:
a2[:2 ,1: ]

array([[1, 2, 3],
       [5, 6, 7]])

In [70]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [71]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [72]:
a3[0,1,:]

array([3, 4, 5])

In [73]:
a3[1,:,1]

array([10, 13, 16])

In [74]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [75]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [76]:
# iterating
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [79]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [80]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [81]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [82]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [83]:
# reshaping
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [85]:
# ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [86]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [87]:
# stacking and splitting (horizontal, vertical)
a1 = np.arange(6)
a1

array([0, 1, 2, 3, 4, 5])

In [88]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
np.hstack((a1, a1))

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [90]:
np.vstack((a2, a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
np.hsplit(a2, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [92]:
np.vsplit(a3, 3)

[array([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]]),
 array([[[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]),
 array([[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])]

In [93]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt # for data visualization
import seaborn as sns 
%matplotlib inline
sns.set(color_codes=True)